// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWnmBULDccwT0JLnOtZLw9z5AMnUbJBCY',
    appId: '1:851528457652:web:309824eedda91c1e15e6e1',
    messagingSenderId: '851528457652',
    projectId: 'multi-vendor-shop-1f7cd',
    authDomain: 'multi-vendor-shop-1f7cd.firebaseapp.com',
    storageBucket: 'multi-vendor-shop-1f7cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpmp6LFQ2IltS_MnbbiNx7W_3X02YgCkI',
    appId: '1:851528457652:android:36b99b03990ab51215e6e1',
    messagingSenderId: '851528457652',
    projectId: 'multi-vendor-shop-1f7cd',
    storageBucket: 'multi-vendor-shop-1f7cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA84BkEalcVejnlDY66QCEuz-wL4fNBsIU',
    appId: '1:851528457652:ios:801bd92b4d0499fa15e6e1',
    messagingSenderId: '851528457652',
    projectId: 'multi-vendor-shop-1f7cd',
    storageBucket: 'multi-vendor-shop-1f7cd.appspot.com',
    iosBundleId: 'com.example.multiVendorShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA84BkEalcVejnlDY66QCEuz-wL4fNBsIU',
    appId: '1:851528457652:ios:7579f7ad30442fcb15e6e1',
    messagingSenderId: '851528457652',
    projectId: 'multi-vendor-shop-1f7cd',
    storageBucket: 'multi-vendor-shop-1f7cd.appspot.com',
    iosBundleId: 'com.example.multiVendorShopApp.RunnerTests',
  );
}
